import Link from "next/link";
import { BarChart3, CircleUserRound, CreditCard, ExternalLink, Home, LayoutGrid, LogOut, Package, Palette, Settings, ShieldCheck, ShoppingCart, Users } from "lucide-react";
import { Brand } from "@/components/brand";
import { logout } from "@/app/dashboard/actions";

const items = [
  ["Visao geral", "/dashboard", Home], ["Produtos", "/dashboard/produtos", Package], ["Categorias", "/dashboard/categorias", LayoutGrid], ["Pedidos", "/dashboard/pedidos", ShoppingCart], ["Clientes", "/dashboard/clientes", Users], ["Relatorios", "/dashboard/relatorios", BarChart3], ["Planos", "/dashboard/planos", CreditCard],
] as const;

export function DashboardShell({ children, storeSlug, isAdmin }: { children: React.ReactNode; storeSlug?: string; isAdmin?: boolean }) {
  return <div className="min-h-screen bg-[#f5f7f6]">
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-64 border-r border-slate-200 bg-white px-4 py-6 lg:block"><div className="px-2"><Brand/></div><nav className="mt-9 space-y-1">{items.map(([label, href, Icon], i)=><Link key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold transition ${i===0 ? "bg-emerald-50 text-brand" : "text-slate-500 hover:bg-slate-50 hover:text-slate-900"}`}><Icon size={19}/>{label}</Link>)}</nav><div className="mt-8 border-t border-slate-100 pt-6"><p className="mb-2 px-3 text-[10px] font-black uppercase tracking-widest text-slate-400">Minha loja</p><Link href="/dashboard/personalizar" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-slate-500 hover:bg-slate-50"><Palette size={19}/>Personalizar</Link><Link href="/dashboard/configuracoes" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-slate-500 hover:bg-slate-50"><Settings size={19}/>Configuracoes</Link></div>{isAdmin&&<div className="mt-6 border-t border-slate-100 pt-6"><p className="mb-2 px-3 text-[10px] font-black uppercase tracking-widest text-slate-400">Administracao</p><Link href="/dashboard/admin" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-slate-500 hover:bg-slate-50"><ShieldCheck size={19}/>Admin global</Link></div>}<form action={logout} className="absolute inset-x-4 bottom-5"><button className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-sm font-bold text-slate-500 hover:bg-red-50 hover:text-red-600"><LogOut size={19}/>Sair</button></form></aside>
    <div className="lg:pl-64"><header className="sticky top-0 z-30 flex h-18 items-center justify-between border-b border-slate-200 bg-white/90 px-5 backdrop-blur lg:px-8"><div><p className="text-xs font-bold text-slate-400">PAINEL DA LOJA</p><h1 className="font-display text-lg font-extrabold">MGD Catalogo PRO</h1></div><div className="flex items-center gap-2">{storeSlug && <Link target="_blank" href={`/loja/${storeSlug}`} className="hidden items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-bold sm:flex"><ExternalLink size={17}/>Ver minha loja</Link>}<button className="grid size-10 place-items-center rounded-xl bg-slate-100"><CircleUserRound size={21}/></button></div></header><main className="p-5 lg:p-8">{children}</main></div>
  </div>;
}
