import Link from "next/link";
import { ArrowRight, Box, Eye, Package, ShoppingBag, Users } from "lucide-react";
import { createClient } from "@/lib/supabase/server";
import { OnboardingForm } from "@/components/onboarding-form";

export default async function DashboardPage() {
  const supabase = await createClient();
  if (!supabase) return <SetupRequired/>;
  const { data: store } = await supabase.from("stores").select("id,name,slug").maybeSingle();
  if (!store) return <OnboardingForm/>;
  const [{ count: products }, { count: orders }, { count: customers }, { count: visits }] = await Promise.all([
    supabase.from("products").select("id", { count: "exact", head: true }), supabase.from("orders").select("id", { count: "exact", head: true }), supabase.from("customers").select("id", { count: "exact", head: true }), supabase.from("store_visits").select("id", { count: "exact", head: true }),
  ]);
  const metrics = [["Produtos",products||0,Package,"bg-violet-50 text-violet-600"],["Pedidos",orders||0,ShoppingBag,"bg-orange-50 text-orange-600"],["Clientes",customers||0,Users,"bg-blue-50 text-blue-600"],["Visitas",visits||0,Eye,"bg-emerald-50 text-brand"]] as const;
  return <div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-slate-400">BEM-VINDO AO SEU NEGOCIO</p><h2 className="font-display mt-1 text-3xl font-extrabold">Ola, {store.name}</h2><p className="mt-2 text-slate-500">Acompanhe o desempenho da sua loja hoje.</p></div><Link href="/dashboard/produtos/novo" className="flex h-11 items-center justify-center gap-2 rounded-xl bg-brand px-5 text-sm font-extrabold text-white"><Package size={18}/>Novo produto</Link></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,Icon,color])=><div key={label} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><span className={`grid size-11 place-items-center rounded-xl ${color}`}><Icon size={21}/></span><span className="text-xs font-bold text-slate-400">Total</span></div><p className="font-display mt-5 text-3xl font-extrabold">{value}</p><p className="text-sm font-semibold text-slate-500">{label}</p></div>)}</div><div className="mt-6 grid gap-6 xl:grid-cols-[1.4fr_.6fr]"><div className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-display text-lg font-extrabold">Pedidos da semana</h3><div className="mt-6 grid h-56 place-items-center rounded-xl bg-slate-50"><div className="text-center text-slate-400"><ShoppingBag className="mx-auto mb-3"/><p className="font-bold">Os pedidos aparecerao aqui</p><p className="mt-1 text-sm">Compartilhe sua loja para comecar a vender.</p></div></div></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><h3 className="font-display text-lg font-extrabold">Comece por aqui</h3><div className="mt-5 space-y-3"><Link href="/dashboard/produtos/novo" className="flex items-center justify-between rounded-xl bg-emerald-50 p-4 text-sm font-extrabold text-brand"><span className="flex items-center gap-2"><Box size={18}/>Cadastrar produto</span><ArrowRight size={17}/></Link><Link href={`/loja/${store.slug}`} className="flex items-center justify-between rounded-xl bg-slate-50 p-4 text-sm font-extrabold"><span className="flex items-center gap-2"><Eye size={18}/>Visualizar loja</span><ArrowRight size={17}/></Link></div></div></div></div>;
}

function SetupRequired(){return <div className="mx-auto max-w-2xl rounded-3xl border border-amber-200 bg-amber-50 p-8"><h2 className="font-display text-2xl font-extrabold">Conecte seu Supabase</h2><p className="mt-3 leading-7 text-slate-600">Copie <code>.env.example</code> para <code>.env.local</code>, informe as chaves do projeto e execute a migracao SQL. A interface ja esta pronta para usar dados reais.</p></div>}
